export const CLIENT_REQUEST = 'CLIENT_REQUEST';
export const CLIENT_SUCCESS = 'CLIENT_SUCCESS';
export const CLIENT_FAIL = 'CLIENT_FAIL';

export const CLIENT_BY_ID_REQUEST = 'CLIENT_BY_ID_REQUEST';
export const CLIENT_BY_ID_SUCCESS = 'CLIENT_BY_ID_SUCCESS';
export const CLIENT_BY_ID_FAIL = 'CLIENT_BY_ID_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
