export const GET_ALL_QUOTES_REQUEST = 'GET_ALL_QUOTES_REQUEST';
export const GET_ALL_QUOTES_SUCCESS = 'GET_ALL_QUOTES_SUCCESS';
export const GET_ALL_QUOTES_FAIL = 'GET_ALL_QUOTES_FAIL';

export const GET_QUOTE_BY_ID_REQUEST = 'GET_QUOTE_BY_ID_REQUEST';
export const GET_QUOTE_BY_ID_SUCCESS = 'GET_QUOTE_BY_ID_SUCCESS';
export const GET_QUOTE_BY_ID_FAIL = 'GET_QUOTE_BY_ID_FAIL';

export const CREATE_QUOTE_REQUEST = 'CREATE_QUOTE_REQUEST';
export const CREATE_QUOTE_SUCCESS = 'CREATE_QUOTE_SUCCESS';
export const CREATE_QUOTE_FAIL = 'CREATE_QUOTE_FAIL';

export const UPDATE_QUOTE_REQUEST = 'UPDATE_QUOTE_REQUEST';
export const UPDATE_QUOTE_SUCCESS = 'UPDATE_QUOTE_SUCCESS';
export const UPDATE_QUOTE_FAIL = 'UPDATE_QUOTE_FAIL';

export const DELETE_QUOTE_REQUEST = 'DELETE_QUOTE_REQUEST';
export const DELETE_QUOTE_SUCCESS = 'DELETE_QUOTE_SUCCESS';
export const DELETE_QUOTE_FAIL = 'DELETE_QUOTE_FAIL';

export const QUOTE_RESET = 'QUOTE_RESET';
